@host = http://localhost
@port = 3000
@version = /api/v1


###
GET {{host}}:{{port}}{{version}}/

###
GET {{host}}:{{port}}/json/kotlinx-serialization

###
POST {{host}}:{{port}}{{version}}/users
Content-Type: application/json

{
    "email": "intelliJ",
    "password": "123456"
}

###
# @name  auth_token
POST {{host}}:{{port}}{{version}}/auth/login
Content-Type: application/json

{
    "userName": "intelliJ",
    "password": "123456"
}

###
GET {{host}}:{{port}}{{version}}/users/hello
Authorization: Bearer {{auth_token.response.body.token}}

###
GET {{host}}:{{port}}{{version}}/users/{{auth_token.response.body.user.id}}
Authorization: Bearer {{auth_token.response.body.token}}

###
PUT {{host}}:{{port}}{{version}}/users/{{auth_token.response.body.user.id}}
Authorization: Bearer {{auth_token.response.body.token}}
Content-Type: application/json

{
    "password": "123456"
}

###
DELETE {{host}}:{{port}}{{version}}/users/{{auth_token.response.body.user.id}}
Authorization: Bearer {{auth_token.response.body.token}}